# Site settings
title: Willy's Farm and Cider Mill
subtitle: "Get Outside with Your Family."
url: "https://willysfarm.com"
baseurl: "https://willysfarm.com"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Google Schema
# JSON
type: "LocalBusiness"
name: "Willy's Farm and Cider Mill"
email: "thefamily@willysfarm.com"
foundingDate: "1980-05-20"

# Links to include in menu navigation
links:
  - title: Home
    url: /index.html
  - title: Get Directions
    url: /get-directions.html
  - title: Things to do
    url: /things-to-do.html
  - title: Custom Pressing
    url: /custom-pressing.html
  - title: Our Story
    url: /our-story.html 
  - title: Hours
    url: /hours.html
             
# Links to Social Media
social:
  - name: Instagram
    url: https://instagram.com/willysfarm
  - name: Facebook
    url: https://www.facebook.com/willysfarm/

# Google Analytics
google-analytics: "UA-106752861-1"

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"