# Site settings
title: Willy's Farm and Cider Mill
subtitle: "Get Outside with Your Family."
url: "http://willysfarm.com" # the base hostname & protocol for your site
baseurl: #"/willys-farm"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Google Schema
# JSON
context: "http://schema.org"
type: "LocalBusiness"
name: "Willy's Farm and Cider Mill"
url: "http://willysfarm.com"
email: "thefamily@willysfarm.com"
logo: "http://patrickhanus.com/tile.png"
sameAs: "https://www.instagram.com/thehsedition/"

# Google Analytics
google-analytics: "UA-XXXX-1"

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"